export const TRANSCRIPT_TOGGLE = 'TRANSCRIPT_TOGGLE';
export const TRANSCRIPT_SEND_MESSAGE = 'TRANSCRIPT_SEND_MESSAGE';
export const TRANSCRIPT_PUSH_MESSAGE = 'TRANSCRIPT_PUSH_MESSAGE';

export const SET_PERSONA_STATE = 'SET_PERSONA_STATE';
export const SET_VIDEO_BOUNDS = 'SET_VIDEO_BOUNDS';

export const SCENE_START_VIDEO = 'SCENE_START_VIDEO';
export const SCENE_START_AUDIO = 'SCENE_START_AUDIO';
export const SCENE_CONNECTED = 'SCENE_CONNECTED';
export const SCENE_DISCONNECTED = 'SCENE_DISCONNECTED';

export const SET_FEATURES = 'SET_FEATURES';
export const TOGGLE_MUTE = 'TOGGLE_MUTE';
export const TOGGLE_PAUSE = 'TOGGLE_PAUSE';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const CHANGE_PANEL = 'CHANGE_PANEL';
export const TOGGLE_INFO_PANEL = 'TOGGLE_INFO_PANEL';
export const ANIMATE_CAMERA = 'ANIMATE_CAMERA';
export const SET_USER_SPEAKING = 'SET_USER_SPEAKING';
export const HIDE_CARDS = 'HIDE_CARDS';
export const SET_BUSY = 'SET_BUSY';
export const SET_ERROR = 'SET_ERROR';
